name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: hakanssn
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#nixosConfigurations.gattsu.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.gattsu.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
      - run: nix build -L --no-link .#nixosConfigurations.falconia.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.falconia.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
      - run: nix build -L --no-link .#nixosConfigurations.rickert.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.rickert.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
