name: Update

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - run: nix flake update
      - run: nix flake check
      - uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
          commit_message: "bump"
