name: Update

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Cachix
        uses: cachix/cachix-action@v16
        with:
          name: hakanssn
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#nixosConfigurations.gattsu.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.gattsu.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
      - run: nix build -L --no-link .#nixosConfigurations.falconia.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.falconia.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
      - run: nix build -L --no-link .#nixosConfigurations.rickert.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.rickert.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push hakanssn
      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "ci: bump"
